from functools import lru_cache
import re

# Dictionary of common abbreviations and their expansions for TTS.
# This dictionary can be extended with more abbreviations, slang and languages.
# Keys are the abbreviations (case-insensitive matching will be applied).
# Values are the desired spoken form.
abbreviations = {"pl": {
    # --- Skróty ogólne i popularne ---
    "np.": "na przykład",
    "m.in.": "między innymi",
    "itd.": "i tak dalej",
    "itp.": "i tym podobne",
    "tzn.": "to znaczy",
    "tj.": "to jest",
    "wg": "według",
    "tzw.": "tak zwany",
    "ds.": "do spraw",
    "cdn.": "ciąg dalszy nastąpi",
    "cd.": "ciąg dalszy",
    "ww.": "wyżej wymieniony",
    "jw.": "jak wyżej",
    "br.": "bieżącego roku",
    "ub. r.": "ubiegłego roku",
    "p.n.e.": "przed naszą erą",
    "n.e.": "naszej ery",
    "A.D.": "roku pańskiego",
    "PS": "post scriptum",
    "vs": "versus",
    "etc.": "et cetera",
    "pt.": "pod tytułem",
    "zob.": "zobacz",
    "por.": "porównaj",
    "załącz.": "załącznik",
    "red.": "redakcja",
    "wz.": "w zastępstwie",
    "p.o.": "pełniący obowiązki",

    # --- Tytuły, stopnie, formy grzecznościowe ---
    "dr": "doktor",
    "prof.": "profesor",
    "mgr": "magister",
    "inż.": "inżynier",
    "hab.": "habilitowany",
    "lek.": "lekarz",
    "wet.": "weterynarii",
    "płk": "pułkownik",
    "gen.": "generał",
    "ks.": "ksiądz",
    "św.": "świętego",
    "bł.": "błogosławionego",
    "dyr.": "dyrektor",
    "prez.": "prezydent",
    "s.a.": "spółka akcyjna",
    "sp. z o.o.": "spółka zoo",
	"sp.": "spółka",
    "z o.o.": "zo",

    # --- Jednostki miar i wielkości ---
    "zł": "złotych",
    "gr": "groszy",
    "kg": "kilogram",
    "dag": "dekagram",
    "km": "kilometr",
    "m": "metr",
    "cm": "centymetr",
    "mm": "milimetr",
    "ml": "mililitr",
    "ha": "hektar",
    "a": "ar",
    "godz.": "godzina",
    "min.": "minuta",
    "s": "sekunda",
    "proc.": "procent",
    "°C": "stopni Celsjusza",
    "V": "wolt",
    "km/h": "kilometrów na godzinę",
    "hPa": "hektopaskali",
    "kcal": "kilokalorii",

    # --- Nazwy własne, instytucje, organizacje ---
    "NFZ": "en ef zet",
    "NBP": "en be pe",
    "PKP": "pe ka pe",
    "PKS": "pe ka es",
    "PKO": "pe kao",
    "PZU": "pe zet u",
    "AGH": "a gie ha",
    "UW": "u wu",
    "UJ": "u jot",
    "SGH": "es gie ha",
    "PW": "pe wu",
    "MON": "mon",
    "MSW": "em es wu",
    "MSZ": "em es zet",
    "ONZ": "o en zet",
    "UE": "unia europejska",
    "USA": "u es a",
    "CBŚ": "ce be ś",
    "CBA": "ce be a",
    "ABW": "a be wu",
    "IPN": "i pe en",
    "KNF": "ka en ef",
    "PCK": "pe ce ka",
    "ZHP": "zet ha pe",
    "TVP": "te fau pe",
    "TVN": "te fau en",
    "CBOS": "cebos",
    "KRS": "ka er es",
    "UOKiK": "u o kik",
    "RP": "er pe",
    "PRL": "pe er el",
    "PZPR": "pe zet pe er",
    "SLD": "es el de",
    "PSL": "pe es el",
    "PO": "pe o",
    "PiS": "pis",
    "NATO": "nato",
    "ZSRR": "zet es er er",
    "AK": "Armia Krajowa",
    "SB": "es be",
    "MO": "em o",
    "II RP": "druga rzeczpospolita",
    "III RP": "trzecia rzeczpospolita",
    "Poczta Pol.": "poczta polska",

    # --- Technika, biznes, medycyna, internet ---
    "VAT": "wat",
    "PKB": "pe ka be",
    "PKD": "pe ka de",
    "BHP": "be ha pe",
    "PPOŻ": "pe poż",
    "CEIDG": "ce i de gie",
    "ISBN": "i es be en",
    "GPS": "gie pe es",
    "AGD": "a gie de",
    "RTV": "er te fau",
    "PC": "pe cet",
    "IT": "aj ti",
    "WWW": "wu wu wu",
    "SMS": "es em es",
    "MMS": "em em es",
    "URL": "u er el",
    "HDMI": "ha de em i",
    "USB": "u es be",
    "Wi-Fi": "wi fi",
    "E-mail": "imejl",
    "CD": "si di",
    "DVD": "di wi di",
    "VIP": "wip",
    "CV": "si wi",
    "FAQ": "najczęściej zadawane pytania",
    "DIY": "di aj łaj",
    "ASAP": "jak najszybciej",
    "CEO": "si i oł",
    "HR": "ha er",
    "PR": "pi ar",
    "IQ": "aj kju",
    "EKG": "e ka gie",
    "EEG": "e e gie",
    "RTG": "er te gie",
    "USG": "u es gie",
    "DNA": "de en a",
    "RNA": "er en a",
    "AIDS": "ejds",
    "HIV": "hiw",
    "RM": "rezonans magnetyczny",
    "TK": "tomografia komputerowa",
    "NFC": "en ef ce",
    "LED": "led",
    "LCD": "el si di",
    "UFO": "ufo",
    "SOR": "sor",

    # --- Mowa potoczna, slang, skróty z komunikatorów ---
    "thx": "dzięki",
    "btw": "przy okazji",
    "omg": "o mój boże",
    "lol": "lol",
    "zw": "zaraz wracam",
    "wgl": "w ogóle",
    "cb": "ciebie",
    "sb": "sobie",
    "kc": "kocham cię",
    "jn": "jak nie",
    "w-f": "wu ef",
    "wf": "wu ef",
    "xd": "iks de",
    "wawa": "warszawa",
    "krk": "kraków",
    "wro": "wrocław",
    "priv": "prywatna wiadomość",
    "tbh": "szczerze powiedziawszy",
    "imho": "moim skromnym zdaniem",
    "nvm": "nieważne",
    "idk": "nie wiem",
    "jj": "już jestem",
    "sql": "es ku el",
    "js": "dżejes",
    "css": "ce es es",
    "html": "ha te em el",

    # --- Adresy i oznaczenia prawne (z kropką i bez) ---
    "ul.": "ulica",
    "al.": "aleja",
    "al": "aleja",
    "os.": "osiedle",
    "pl.": "plac",
    "woj.": "województwo",
    "pow.": "powiat",
    "gm.": "gmina",
    "gm": "gmina",
    "płn.": "północny",
    "płd.": "południowy",
    "wsch.": "wschodni",
    "zach.": "zachodni",
    "m.st.": "miasto stołeczne",
    "wlkp.": "Wielkopolska",
    "śl.": "Śląsk",
    "art.": "artykuł",
    "ust.": "ustęp",
    "par.": "paragraf",
    "pkt": "punkt",
    "nr": "numer",
    "r.": "rok",
    "w.": "wiek",
    "s.": "strona",
    "str.": "strona",
    "t.": "tom",

    # --- Wyliczanie ---
    "1.": "Po pierwsze.",
    "2.": "Po drugie.",
    "3.": "Po trzecie.",
    "4.": "Po czwarte.",
    "5.": "Po piąte.",
    "6.": "Po szóste.",
    "7.": "Po siódme.",
    "8.": "Po ósme.",
    "9.": "Po dziewiąte.",
    "10.": "Po dziesiąte.",

},
"en":{
    # Common General Abbreviations
    "ASAP": "as soon as possible",
    "BTW": "by the way",
    "FYI": "for your information",
    "LOL": "laugh out loud",
    "OMG": "oh my god",
    "BRB": "be right back",
    "TTYL": "talk to you later",
    "LMK": "let me know",
    "NVM": "never mind",
    "SMH": "shaking my head",
    "IMO": "in my opinion",
    "IMHO": "in my humble opinion",
    "ROFL": "rolling on the floor laughing",
    "AFAIK": "as far as I know",
    "TMI": "too much information",
    "TBH": "to be honest",
    "ICYMI": "in case you missed it",
    "THX": "thanks",
    "TY": "thank you",
    "TYSM": "thank you so much",
    "YW": "you're welcome",
    "YOLO": "you only live once",
    "QOTD": "quote of the day",
    "AFK": "away from keyboard",
    "IRL": "in real life",
    "DAE": "does anyone else",
    "JK": "just kidding",
    "IDK": "I don't know",
    "IDC": "I don't care",
    "IKR": "I know, right",
    "NGL": "not gonna lie",
    "HMU": "hit me up",
    "FWIW": "for what it's worth",
    "WYD": "what are you doing",
    "RN": "right now",
    "GTG": "got to go",
    "G2G": "got to go",
    "CU": "see you",
    "Cya": "see ya",
    "B4": "before",
    "BC": "because",
    "JIC": "just in case",
    "FOMO": "fear of missing out",
    "POV": "point of view",
    "TBA": "to be announced",
    "TBD": "to be decided",
    "DIY": "do it yourself",
    "FTFY": "fixed that for you",
    "GG": "good game",
    "NBD": "no big deal",
    "EOD": "end of day",
    "EOW": "end of week",
    "COB": "close of business",
    "ETA": "estimated time of arrival",
    "CC": "carbon copy", # or "credit card" depending on context - keep this in mind
    "BCC": "blind carbon copy",
    "FAQ": "frequently asked questions",
    "AKA": "also known as",
    "NP": "no problem",
    "N/A": "not applicable", # or "not available" - context matters
    "OOO": "out of office",
    "TIA": "thanks in advance",
    "NSFW": "not safe for work",
    "WFH": "work from home",
    "OMW": "on my way",
    "BRT": "be right there",
    "TBF": "to be frank", # or "to be fair" - context matters
    "TGIF": "thank goodness it's Friday",
    "TBT": "throwback Thursday",
    "TIL": "today I learned",
    "AMA": "ask me anything",
    "ELI5": "explain like I'm 5",
    "XOXO": "hugs and kisses",
    "HBD": "happy birthday",
    "W/E": "whatever", # Could also be "weekend" - context matters
    "WTF": "what the f", # Sensitive, consider context/policy
    "WYSIWYG": "what you see is what you get",
    "GOAT": "greatest of all time",
    "DM": "direct message",
    "PM": "private message",
    "OP": "original poster",
    "IRL": "in real life",
    "AFK": "away from keyboard",


    # Business/Professional (some overlap with general)
    "B2B": "business to business",
    "B2C": "business to consumer",
    "CSR": "corporate social responsibility",
    "DEI": "diversity, equity, and inclusion",
    "P/E": "price to earnings",
    "EBITDA": "earnings before interest, taxes, depreciation, and amortization",
    "CEO": "chief executive officer",
    "CFO": "chief financial officer",
    "COO": "chief operating officer",
    "HR": "human resources",
    "PR": "public relations",
    "KPI": "key performance indicator",
    "ROI": "return on investment",
    "UX": "user experience",
    "UI": "user interface",
    "CRM": "customer relationship management",
    "SME": "subject matter expert",
    "SMB": "small and medium business",
    "SaaS": "software as a service",
    "TOS": "terms of service",
    "SLA": "service level agreement",
    "R&D": "research and development",
    "RFP": "request for proposal",
    "RFI": "request for information",
    "PO": "purchase order",
    "MOU": "memorandum of understanding",
    "NDA": "non-disclosure agreement",
    "EOD": "end of day",
    "ETA": "estimated time of arrival",
    "WIP": "work in progress",
    "POC": "proof of concept",


    # Technology/Internet Specific (often pronounced as letters or words)
    "HTML": "H T M L",
    "CSS": "C S S",
    "HTTP": "H T T P",
    "HTTPS": "H T T P S",
    "URL": "U R L",
    "VPN": "V P N",
    "USB": "U S B",
    "Wi-Fi": "wi fi",
    "AI": "A I",
    "ML": "M L",
    "API": "A P I",
    "CPU": "C P U",
    "RAM": "R A M",
    "PDF": "P D F",
    "FAQ": "F A Q", # Or "frequently asked questions"
    "JPEG": "jay peg",
    "GIF": "gif", # or "jif" - depends on preference
    "SMS": "S M S",
    "MMS": "M M S",
    "GPS": "G P S",
    "CD": "C D",
    "DVD": "D V D",
    "Blu-ray": "blue ray",
    "NASA": "NASA", # pronounced as a word
    "NATO": "NATO", # pronounced as a word
    "FBI": "F B I",
    "CIA": "C I A",
    "UN": "U N",
    "EU": "E U",
    "CEO": "C E O",
    "CFO": "C F O",
    "COO": "C O O",
    "WWW": "world wide web",


    # Shortened words (often pronounced as full words)
    "abt": "about",
    "b/c": "because",
    "cuz": "because",
    "thru": "through",
    "nite": "night",
    "2moro": "tomorrow",
    "2nite": "tonight",
    "gr8": "great",
    "l8r": "later",
    "pls": "please",
    "plz": "please",
    "u": "you",
    "ur": "your", # or "you are"
    "r": "are",
    "msg": "message",
    "pic": "picture",
    "info": "information",
    "vid": "video",
    "yr": "year",
    "mo": "month",
    "wk": "week",
    "bday": "birthday",
    "bro": "brother",
    "sis": "sister",
    "fam": "family",
    "pfp": "profile picture",
    "srsly": "seriously",
    "kinda": "kind of",
    "sorta": "sort of",


    # Punctuation/Symbols (how they might be read)
    "&": "and",
    "@": "at",
    "$$$": "dollars", # or "money"
    "w/": "with",
    "w/o": "without",
    "Dr.": "doctor",
    "Mr.": "mister",
    "Mrs.": "missus",
    "Ms.": "miss",
    "St.": "saint", # or "street" depending on context
    "Ave.": "avenue",
    "Rd.": "road",
    "Blvd.": "boulevard",
    "P.S.": "postscript",
    "e.g.": "for example",
    "i.e.": "that is",
    "vs.": "versus",
    "etc.": "et cetera",
    "approx.": "approximately",
    "max.": "maximum",
    "min.": "minimum",
    "vol.": "volume",
    "fig.": "figure",
    "chap.": "chapter",
    "p.": "page",
    "pp.": "pages",
    "No.": "number",
    "Cpt.": "captain",
    "Lt.": "lieutenant",
    "Gen.": "general",
    "Col.": "colonel",
    "Sgt.": "sergeant",
    "A.M.": "A M", # ante meridiem
    "P.M.": "P M", # post meridiem
    "B.C.": "B C", # before Christ
    "A.D.": "A D", # anno domini
    "CEO.": "C E O", # Sometimes seen with a period
    "Ltd.": "limited",
    "Inc.": "incorporated",
    "Co.": "company",
    "Corp.": "corporation",
    "Dept.": "department",
    "Jan.": "january",
    "Feb.": "february",
    "Mar.": "march",
    "Apr.": "april",
    "Jun.": "june",
    "Jul.": "july",
    "Aug.": "august",
    "Sep.": "september",
    "Oct.": "october",
    "Nov.": "november",
    "Dec.": "december",
    "Mon.": "monday",
    "Tue.": "tuesday",
    "Wed.": "wednesday",
    "Thu.": "thursday",
    "Fri.": "friday",
    "Sat.": "saturday",
    "Sun.": "sunday",

}}

abbrev_pattern = None
chosen_abbreviations = None
def compile_abbreviations(language = "en"):
    global abbrev_pattern, chosen_abbreviations
    abbrev_pattern = re.compile(r'(?<!\w)(' + '|'.join(re.escape(k) for k in abbreviations.get(language, abbreviations["en"]).keys()) + r')(?!\w)', re.I)
    chosen_abbreviations = abbreviations.get(language, abbreviations["en"])

def replace_common_abbreviations(text):
    if abbrev_pattern is None:
        compile_abbreviations()
    @lru_cache(maxsize=1024)
    def expand_abbrev_cached(abbrev):
        # Try all casing variants to find a match
        for variant in (abbrev, abbrev.lower(), abbrev.upper(), abbrev.capitalize()):
            if variant in chosen_abbreviations:
                return chosen_abbreviations[variant]
        return abbrev  # If no match, return original

    return abbrev_pattern.sub(lambda m: expand_abbrev_cached(m.group(1)), text)
